version: "3.3"
services:
  redis:
    container_name: redis
    image: bitnami/redis:5.0
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 20000
    command:
      - /run.sh
      # 只需要一个 db
      - --databases 1
      # 不保存数据到硬盘，单纯作为缓存服务器使用
      - --save ""
      # 关闭 AOF （Append-only file）数据持久化（默认是启用的）
      - --appendonly no
      # 内存用尽时，驱逐旧数据
      - --maxmemory-policy volatile-ttl
      # 最大连接数
      - --maxclients 10000
      # 最大内存使用量
      - --maxmemory 1000mb
    environment:
      REDIS_PASSWORD: "change_me"
    ports:
      - "6379:6379"
