---
# 构建所有 CI 用的基础镜像
# Workflow triggers one or more workflow and manage it.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-all-images
spec:
  arguments:
    parameters:
      - name: build-golang-alpine
        value: "true"
      - name: build-flutter-ubuntu
        value: "true"
      - name: build-pulumi-proxmox
        value: "true"
  entrypoint: main
  templates:
    - name: main
      inputs:
        artifacts:
        - name: git-repo
          git:
            # git 仓库内容：CI 镜像的 Dockerfiles 及其他相关文件
            repo: git@gitlab.svc.local:sre-team/workflow-dockerfiles.git
            revision: main
            insecureIgnoreHostKey: true
            usernameSecret:
              name: private-git-creds
              key: username
            sshPrivateKeySecret:
              name: private-git-creds
              key: ssh-private-key
      steps:
        - - name: build-golang-alpine
            templateRef:
              name: build-image  # WorkflowTemplate name
              template: build-image  # template name
            arguments:
              artifacts:
                - name: git-repo
                  from: "{{inputs.artifacts.git-repo}}"
              parameters:
                - name: context-path
                  value: common
                - name: dockerfile
                  value: Dockerfile.golang-alpine
                - name: image
                  value: registry.svc.local/ci/golang:alpine
            when: "{{workflow.parameters.build-golang-alpine}} == true"
          - name: build-flutter-ubuntu
            templateRef:
              name: build-image  # WorkflowTemplate name
              template: build-image  # template name
            arguments:
              artifacts:
                - name: git-repo
                  from: "{{inputs.artifacts.git-repo}}"
              parameters:
                - name: context-path
                  value: common
                - name: dockerfile
                  value: Dockerfile.flutter-ubuntu
                - name: image
                  value: registry.svc.local/ci/flutter:ubuntu
            when: "{{workflow.parameters.build-flutter-ubuntu}} == true"
          - name: build-pulumi-proxmox
            templateRef:
              name: build-image  # WorkflowTemplate name
              template: build-image  # template name
            arguments:
              artifacts:
                - name: git-repo
                  from: "{{inputs.artifacts.git-repo}}"
              parameters:
                - name: context-path
                  value: pulumi_proxmox
                - name: dockerfile
                  value: Dockerfile
                - name: image
                  value: registry.svc.local/ci/pulumi_proxmox:latest
            when: "{{workflow.parameters.build-pulumi-proxmox}} == true"
