version: "3"
services:
  proxy:
    image: "envoyproxy/envoy:v1.21.1"
    container_name: "envoy"
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
      - "15000:15000"  # 仅测试用，直接暴露 admin 端口是非常危险的
    volumes:
      - "./envoy.yaml:/etc/envoy/envoy.yaml"
    networks:
    - proxy

networks: 
  proxy: