version: "3"
services:
  proxy:
    image: "envoyproxy/envoy:v1.21.1"
    container_name: "envoy"
    restart: always
    command:
      - envoy
      - --config-path
      - /etc/envoy/envoy.yaml
      - --log-level
      - debug  # trace/debug/info/warn/error
    ports:
      - "80:8080"
      - "443:8443"
      - "15000:15000"  # 仅测试用，直接暴露 admin 端口是非常危险的
    volumes:
      # 动态配置与静态配置二选一
      # - "./static-config.yaml:/etc/envoy/envoy.yaml"
      - "./dynamic-config:/etc/envoy"
    networks:
    - proxy

networks: 
  proxy: